In [3]:
# vectorization->is the process entire number or in bulk operation can be done
import numpy as np

In [7]:
# nbroadcasting
umbers=np.array([1,2,3,4,5])
results=numbers*10
results[(results>30)& (results<50)]
# vectorization
price=np.array([100,200,300])
quantity=np.array([2,4,6])
price*quantity

array([ 200,  800, 1800])

In [8]:
# broadcasting->Broadcasting in NumPy is a feature that allows arithmetic operations between arrays of different shapes without manually changing their dimensions.
# left side rw right side ko chai same hunye


In [11]:
arr=np.array([1,2,3,4,5,6])
arr.shape
arr.reshape(2,3)
arr.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
arr2=np.array([
    [1,2,3],
    [4,5,6]
])
arr2.reshape(3,-1)
# arr2.shape

array([[1, 2],
       [3, 4],
       [5, 6]])